### ISSUE TITLE
Dataset visualisation tool

### ISSUE THREAD

**Issue by mathieuslplante** [McGill-sea-ice/ice-tracker-deformations#29]
Produce a python code to visualise the data that is included in our netcdf outputs. This tool would:

- load the data in a netcdf file
- Select the triangles in a given time-period
- include mapping functions to show a scatter of the tracked features. This could reuse some of the mapping functions used by Beatrice (i.e. showing the start and end points in different colors)
- Include a mapping of the deformation and vorticity in the dataset.

**Comment by LekiYak** [comment]
Hi all,

I'm having issues using ax.tripcolor. Running my code in `src/SatelliteCoverage/plot_from_netcdf.py`, the function `plot_deformations` returns this error:

![image](https://user-images.githubusercontent.com/97495374/180456942-346f5dbf-9ee3-489f-aadb-b22a072b6baa.png)

The arrays `colours` and `triangles` are of the same length, and according to the documentation (https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.tripcolor.html) this should be fine. Does anyone have suggestions on how to fix this?

**Comment by LekiYak** [comment]
The issue has been found and fixed.

**Comment by LekiYak** [comment]
Update on visualising the data from the netCDF file:
The vertices we added to the netCDF file correspond to the indices of the corresponding point (vertex) in the _original data file_. For example, the triangle [213, 34, 106] is formed from the latitude/longitude points found at indices 213, 34, and 106 in the data file (pair of images) corresponding to the triangulation that produced [213, 34, 106]. This means that the proposed vertex additions to the netCDF file rows (#31) **do not necessarily correspond to the triangles those rows represent**. I am currently trying out other approaches.

**Comment by LekiYak** [comment]
Functions to plot the divergence, shear, and vorticity on a basemap from the netCDF have been completed. Bellow is a comparison of the original plotting script that took advantage of the intermediary .csv files (left) and the new script, which reads directly from the netCDF:

![plot comparison](https://user-images.githubusercontent.com/97495374/181606664-4e3bc3f2-3cfa-4927-96dc-79dd9dd1d7bb.png)

**Comment by a-bouchat** [comment]
Awesome! So are you using tripcolor in the end?

**Comment by LekiYak** [comment]
Yes, recreating the lat/lon list was the bottleneck, and once that got fixed it worked. Note that the resolution can and should be improved for future plotting.
