### ISSUE TITLE
Observations and Modification of RIOPS Grid

### ISSUE THREAD

**Issue by phil-blain** [McGill-sea-ice/ice-tracker-deformations#3]
*On GitLab by @bduval2 on May 27, 2021, 13:43*

---

The RIOPS grid is used to organize data points in quadrilaterals. 

**1. Observations**

The following is a short investigation on the positionning of RIOPS grid points:

![Capture_d_écran__27_](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//d1c14b6dc920129aa7b058564cd2b12cdb83bd45ab034ad85fb0c282c1f011f0/Capture_d_écran__27_.png?raw=true)

**2. Modification**

We modify the RIOPS grid to meet the needs of the project. We first roughly define our region of interest:

![zone_dintérêt](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//510b1a0c33552add09a4ab325980af2b16a324faeb995ee9e69f528201d5da1e/zone_dintérêt.jpg?raw=true)

and crop the grid to obtain a new grid that covers the region of interest:

![cropped_grid](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//105dbcddf2ce43edc0f70e7dc1eee9c7c7c1f49fe7cfb37d645e5caa3532e7eb/cropped_grid.png?raw=true)

We create a distances from land matrix by using a grid (in blue below) that covers a slightly greater area than the cropped grid above (in red below):

![coastGrid](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//604eecb6d04b433d11c93181e991c73b3c8b2cd19d85177ceb0758f9d246fd12/coastGrid.png?raw=true)

The distances from land matrix is mapped below:

![Capture_d_écran__124_](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//b1f0a4428a9e2b45868168978265ad344b8b46f5c604b6c0b53c21d55c745701/Capture_d_écran__124_.png?raw=true)

Here, we change the upper bound for the colormap in order to better visualize the smaller distances:

![Capture_d_écran__125_](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//128ae12f587656287e7211d5420cff1e22ba6c1952af32bc8cf679f62fb5fb42/Capture_d_écran__125_.png?raw=true)

Here is a close up of a coast section of the above map:

![Capture_d_écran__126_](../blob/008f4377a287cf19ad7e381b0f39710fa10c4ad1//4d1cb7eb5fa6ca35abe700e849378b909127e9441077c5598416106bddb80fd5/Capture_d_écran__126_.png?raw=true)

Cropped grid (matrices of latitudes and longitudes for *points traceurs* and *points de vitesse*) and the distances from land matrix are stored in a new netcdf file, along with a land-ocean mask.

**Comment by mathieuslplante** [comment]
I am closing. These are weirdly nice satisfying figures!!
