### ISSUE TITLE
Mapping the tracked positions in the netcdf files

### ISSUE THREAD

**Issue by mathieuslplante** [McGill-sea-ice/ice-tracker-deformations#30]
For the years 2020 and 2019, we want to map the tracked positions included in the netcdf in 3 different time period:
- a whole winter (if not too long to produce)
- a whole month
- a 72h time period

I would start with the 72h case, then repeat with the entire month and year. For the 72h case, this could be done by reusing some of Beatrice's code, which showed the start position and end position in different colors.  

This is to double check that the data in our netcdf correspond to what we saw from the raw data.

**Comment by LekiYak** [comment]
The total deformation plot for 2019-2020 appears identical to a plot of all start and end points extracted from the corresponding netCDF file.

**Total deformation**
![20191101_72_tot](https://user-images.githubusercontent.com/97495374/178842506-fdd78fb4-ea8f-432d-9ad4-1c6cdfd83352.png)

**All start/end points**
![20192020_tripoints](https://user-images.githubusercontent.com/97495374/178842946-2d10cd0d-c062-4a6f-8085-5875c96e8bed.png)

**Comment by LekiYak** [comment]
This is a collection of plots, each plot containing four images (2017-2018, 2018-2019, 2019-2020, 2020-2021) representing the spatial coverage achieved in the netCDF files output by the deformation calculator. Note that though the 24-hour interval seems to have better spatial coverage overall, previous investigations into spatio-temporal coverage (heatmaps) revealed that the 24-hour interval has poor temporal coverage. The images also suggest that a combination of 24 and 72 hour intervals must be used to analyze data over multiple winters.

![netcdf spatial coverage](https://user-images.githubusercontent.com/97495374/179847086-810d25cf-5d99-4966-aff2-2f8e8179bcf7.png)
