### ISSUE TITLE
May I know how to run the whole project directly, can you guide me? What is the meaning of each parameter in data.dat?

### ISSUE THREAD

**Issue by LooperzZ** [McGill-sea-ice/ice-tracker-deformations#46]

**Comment by dringeis** [comment]
It is not possible to run the whole project, the input data cannot be shared.

The final treated data can be found here: [https://zenodo.org/records/13936609](https://zenodo.org/records/13936609)

And the description of the dataset and algorithm can be found in this preprint: [https://essd.copernicus.org/preprints/essd-2024-227/](https://essd.copernicus.org/preprints/essd-2024-227/),  the full accepted paper will be soon available online.
